# Generated by Django 5.2.6 on 2025-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
