# Generated by Django 4.2.23 on 2025-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_user_username'),
        ('users', '0003_user_phone'),
    ]

    operations = [
    ]
