# Generated by Django 5.2.6 on 2025-09-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='organizer.event'),
        ),
    ]
