# Generated by Django 4.2.23 on 2025-09-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('BOOKING', 'Booking'), ('EVENT', 'Event')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer'),
        ),
    ]
