# Generated by Django 4.2.23 on 2025-09-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_alter_event_is_active'),
        ('customer', '0004_notification_type_alter_notification_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.organizer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
