# Generated by Django 4.2.23 on 2025-09-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_alter_event_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_faq_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='organizer.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event rating',
                'verbose_name_plural': 'event ratings',
                'db_table': 'event_rating_table',
            },
        ),
    ]
