# Generated by Django 5.2.6 on 2025-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MUSIC', 'music'), ('SPORTS', 'sports'), ('TECH', 'tech'), ('ARTS', 'arts'), ('OTHER', 'other')], default='OTHER', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='event_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'organizer',
                'verbose_name_plural': 'organizers',
                'db_table': 'organizer',
                'ordering': ['-id'],
            },
        ),
    ]
