# Generated by Django 4.2.23 on 2025-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
