# Generated by Django 5.2.6 on 2025-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_remove_event_end_at_remove_event_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
