# Generated by Django 4.2.23 on 2025-08-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_event_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['-id'], 'verbose_name': 'organizer', 'verbose_name_plural': 'organizers'},
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizer.organizer'),
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organizer',
            table='organizer_table',
        ),
    ]
