# Generated by Django 5.2.6 on 2025-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_event_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
