# Generated by Django 4.2.23 on 2025-08-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_alter_event_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizer',
            table='organizer',
        ),
    ]
