# Generated by Django 5.2.6 on 2025-09-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_remove_event_qr_code_event_qr_code_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_seats',
            new_name='ticket_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
    ]
