# Generated by Django 5.2.6 on 2025-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_rename_available_seats_event_ticket_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code_text',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
