# Generated by Django 5.2.6 on 2025-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_event_qr_code_image_alter_event_qr_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=20),
        ),
    ]
