# Generated by Django 5.2.6 on 2025-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_code_text',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
