# Generated by Django 5.2.6 on 2025-09-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_event_qr_code_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(),
        ),
    ]
