# Generated by Django 5.2.6 on 2025-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
