# Generated by Django 5.2.6 on 2025-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_alter_event_images_alter_event_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
